//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes
    {
        public Ordenes()
        {
            this.OrdenDetalles = new HashSet<OrdenDetalles>();
        }
    
        public int OrdenID { get; set; }
        public int UsuarioID { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Total { get; set; }
        public string Estatus { get; set; }
        public string DireccionEntrega { get; set; }
    
        public virtual ICollection<OrdenDetalles> OrdenDetalles { get; set; }
    }
}
