//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    //using Data;
    using System;
    using System.Collections.Generic;
    
    public partial class CarritoItem
    {
        //public int CarritoItemID { get; set; }
        //public int ProductoID { get; set; }
        public int CantidadSeleccionada { get; set; }

        public Producto Producto { get; set; }

        public decimal Total { get  { return Producto.Precio * CantidadSeleccionada ; }   }
    }
}
