//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        //public Producto()
        //{
        //    this.CarritoItem = new HashSet<CarritoItem>();
        //    this.OrdenDetalles = new HashSet<OrdenDetalles>();
        //}
    
        public int ProductoID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public int CantidadDisponible { get; set; }
    
        //public virtual ICollection<CarritoItem> CarritoItem { get; set; }
        //public virtual ICollection<OrdenDetalles> OrdenDetalles { get; set; }
    }
}
